# Generated by Django 3.1.5 on 2021-01-12 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=15, unique=True, verbose_name='Account Number')),
                ('fullname', models.CharField(max_length=150, verbose_name='Full Name')),
                ('account_bal', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Account Balance')),
                ('upd_date', models.DateTimeField(verbose_name='Updated Date')),
                ('account_holder', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Account Holder')),
            ],
            options={
                'verbose_name': 'Account Master',
                'verbose_name_plural': 'Account Master',
                'db_table': 'account_master',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Transaction Amount')),
                ('trx_dt_time', models.DateTimeField(auto_now_add=True, verbose_name='Transact At')),
                ('trx_cur_bal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Current Balance')),
                ('trx_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.accountmaster', verbose_name='Account Number')),
                ('trx_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.lookupmapping', verbose_name='Transaction Type')),
            ],
            options={
                'verbose_name': 'Transaction History',
                'verbose_name_plural': 'Transaction History',
                'db_table': 'transaction_history',
            },
        ),
    ]
