# Generated by Django 3.1.5 on 2021-01-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='trx_last_bal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Last Balance'),
            preserve_default=False,
        ),
    ]
