# Generated by Django 3.1.5 on 2021-01-12 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LookUp',
            fields=[
                ('lu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lu_code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('lu_desc', models.CharField(max_length=100, verbose_name='Description')),
                ('lu_cr_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('lu_upd_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated At')),
                ('lu_cr_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
            ],
            options={
                'verbose_name': 'Look Up',
                'verbose_name_plural': 'Look Up',
                'db_table': 'lookup',
            },
        ),
        migrations.CreateModel(
            name='LookUpMapping',
            fields=[
                ('lum_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lum_code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('lum_desc', models.CharField(max_length=100, verbose_name='Description')),
                ('lum_cr_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('lum_upd_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated At')),
                ('lum_cr_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('lum_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.lookup', verbose_name='LookUp Head')),
            ],
            options={
                'verbose_name': 'Look Up Mapping',
                'verbose_name_plural': 'Look Up Mapping',
                'db_table': 'lookup_mapping',
            },
        ),
    ]
